### GET request to example server
GET http://localhost:8080

###
GET http://localhost:8080/api/v1/software-engineers

###
GET http://localhost:8080/api/v1/software-engineers/3
###

POST http://localhost:8080/api/v1/software-engineers
Content-Type: application/json

{
  "name": "Abod",
  "teckStack": "gemini, node, AI, ML-expert, GO, C++, Java, Spring, Rust"
}

###
POST http://localhost:8080/api/v1/software-engineers
Content-Type: application/json

{
  "name": "Isiah",
  "teckStack": "supabase, ts, next.js"
}

###
DELETE http://localhost:8080/api/v1/software-engineers/1

###
###
PUT http://localhost:8080/api/v1/software-engineers/3
Content-Type: application/json

{
  "name": "John Doe",
  "teckStack": "Java, Spring Boot, PostgreSQL"
}